nohup java -jar CrawlerClientCAS.jar type=1 name=topsearch_crawlerclient project=5 > newss.log&
nohup java -jar CrawlerClientCAS.jar type=2 name=topsearch_crawlerclient project=5 > newsm.log&
nohup java -jar CrawlerClientCAS.jar type=3 name=topsearch_crawlerclient project=5 > bbss.log&
nohup java -jar CrawlerClientCAS.jar type=5 name=topsearch_crawlerclient project=5 > blogs.log&
nohup java -jar CrawlerClientCAS.jar type=7 name=topsearch_crawlerclient project=5 > weibos.log&
nohup java -jar CrawlerClientCAS.jar type=8 name=topsearch_crawlerclient project=5 > weibom.log&
nohup java -jar CrawlerClientCAS.jar type=15 name=topsearch_crawlerclient project=5 > weixins.log&
nohup java -jar CrawlerClientCAS.jar type=21 name=topsearch_crawlerclient project=5 > reports.log&
nohup java -jar CrawlerClientCAS.jar type=37 name=topsearch_crawlerclient project=5 > zhengwus.log&
nohup java -jar CrawlerClientCAS.jar type=39 name=topsearch_crawlerclient project=5 > baokans.log&
nohup java -jar CrawlerClientCAS.jar type=41 name=topsearch_crawlerclient project=5 > waimeis.log&
nohup java -jar CrawlerClientCAS.jar type=45 name=topsearch_crawlerclient project=5 > clients.log&